[workspace]
resolver = "2"
members = ["cli", "core", "wasm"]

[workspace.dependencies]
clap = { version = "4.5.31", features = ["derive", "env"] }
embedded-io = "0.6.1"
paste = "1.0.15"
snafu = "0.8.5"
strum = { version = "0.27.1", default-features = false, features = ["derive"] }
tracing = { version = "0.1.41", default-features = false, features = [
  "attributes",
] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
  "time",
] }
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.100"
wasm-bindgen-test = "0.3.50"
wmf-core = { git = "https://github.com/mythrnr/wmf-rs.git", tag = "0.0.11", package = "wmf-core", default-features = false }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7" }

# workspace
emf-cli = { path = "./cli" }
emf-core = { path = "./core", default-features = false }
emf-wasm = { path = "./wasm" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

# allowed rules
doc_markdown = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
