[package]
name = "emf-wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook", "tracing"]
console_error_panic_hook = ["dep:console_error_panic_hook"]
tracing = ["dep:tracing-wasm", "emf-core/tracing", "wmf-core/tracing"]

[dependencies]
tracing-wasm = { workspace = true, optional = true }
wasm-bindgen = { workspace = true }

emf-core = { workspace = true, features = ["svg"] }
wmf-core = { workspace = true, features = ["svg"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { workspace = true, optional = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[package.metadata.cargo-udeps.ignore]
development = ["wasm-bindgen-test"]
